---
title: Proceedings of Machine Learning Research
booktitle: Proceedings of the Thirteenth Symposium on Conformal and Probabilistic
  Prediction with Applications
shortname: COPA
start: &1 2024-09-09
end: 2024-09-11
published: 2024-09-10
conference_number: '13'
year: '2024'
publisher: PMLR
series: Proceedings of Machine Learning Research
volume: '230'
layout: proceedings
issn: 2640-3498
id: COPA20242024
month: 0
tex_title: Proceedings of the Thirteenth Symposium on Conformal and Probabilistic
  Prediction with Applications
cycles: false
bibtex_editor: Vantini, Simone and Fontana, Matteo and Solari, Aldo and Bostr\"{o}m,
  Henrik and Carlsson, Lars
editor:
- given: Simone
  family: Vantini
- given: Matteo
  family: Fontana
- given: Aldo
  family: Solari
- given: Henrik
  family: Boström
- given: Lars
  family: Carlsson
description: |
  Proceedings of the Thirteenth Symposium on Conformal and Probabilistic Prediction with Applications
    Held in Politecnico di Milano, Milano, Italy on 09-11 September 2024

  Published as Volume 230 by the Proceedings of Machine Learning Research on 10 September 2024.

  Volume Edited by:
    Simone Vantini
    Matteo Fontana
    Aldo Solari
    Henrik Boström
    Lars Carlsson

  Series Editors:
    Neil D. Lawrence
date_str: '09--11 Sep'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v230"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v230
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v230
email: ''
conference:
  name: The 13th Symposium on Conformal and Probabilistic Prediction with Applications
  url: https://copa-conference.com/
  location: Politecnico di Milano, Milano, Italy
  dates:
  - *1
  - 2024-09-10
  - 2024-09-11
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v230/copa_2024.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v230/copa_2024.bib
